# permissions for end users to edit ghosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ghost-controller
    app.kubernetes.io/managed-by: kustomize
  name: ghost-editor-role
rules:
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts/status
  verbs:
  - get
