---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts/events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts/finalizers
  verbs:
  - update
- apiGroups:
  - marketing.kb.dev
  resources:
  - ghosts/status
  verbs:
  - get
  - patch
  - update
